Instructions_stimuli = ['Stimuli/Instructions/Block_over.png',
                        'Stimuli/Instructions/Deliberation1.png',
                        'Stimuli/Instructions/Deliberation2.png',
                        'Stimuli/Instructions/Deliberation3.png',
                        'Stimuli/Instructions/Final_decisions.png',
                        'Stimuli/Instructions/Memory_test.png',
                        'Stimuli/Instructions/no_time_limit.png',
                        'Stimuli/Instructions/Practice.png',
                        'Stimuli/Instructions/Rating.png',
                        'Stimuli/Instructions/Reward_learning1.png',
                        'Stimuli/Instructions/Reward_learning2.png',
                        'Stimuli/Instructions/Session_over.png',
                        'Stimuli/Instructions/start_quiz.png',
                        'Stimuli/Instructions/time_limit.png'];
